export LANDSCAPE_TEXTURE_PATH="img/land_texture.jpg"
export HEIGHT_MAP_PATH="img/map_height.jpeg"
export SKYBOX_RIGHT_PATH="img/right.jpg"
export SKYBOX_LEFT_PATH="img/left.jpg"
export SKYBOX_TOP_PATH="img/up.jpg"
export SKYBOX_BOTTOM_PATH="img/down.jpg"
export SKYBOX_FRONT_PATH="img/front.jpg"
export SKYBOX_BACK_PATH="img/back.jpg"
export MODEL1_PATH="img/12221_Cat_v1_l3.obj"
export MODEL1_TEXTURE_PATH="img/Cat_diffuse.jpg"
export MODEL1_NORMAL_MAP_PATH="img/Cat_bump.jpg"
export MODEL2_PATH="img/12161_Cat_v1_L2.obj"
export MODEL2_TEXTURE_PATH="img/12261_Cat_diffuse.jpg"
export MODEL3_PATH="img/13578_Pallas_Cat_v1_L3.obj"
export MODEL3_TEXTURE_PATH="img/Pallas_Cat_dif.jpg"
./build/OpenGLExample
